apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "medhead"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: medhead
  template:
    metadata:
      labels:
        app: medhead
    spec:
      containers:
        - name: medhead-front
          image: medheadfront:0.0.2
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_URL
              value: "backend.medhead.com"
