FROM gradle:8.5-jdk21 AS build

COPY /MedHeadBackEnd/ /backend/

WORKDIR /backend/

RUN gradle build -x test

FROM openjdk:21

COPY --from=build /backend/build/libs/emergency-0.0.1-SNAPSHOT.jar /app/emergency.jar

ENTRYPOINT ["java", "-jar", "/app/emergency.jar"]