version: 0.0.1

networks:
  my_net:

services:
  mysql:
    image: mysql:latest
    container_name: medheadsql
    ports:
      - 3333:3306
    networks:
      - my_net
    volumes:
      #via un volume docker
      - data:/var/lib/mysql/
      #dans un dossier du projet
      #- .data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medhead

  backend:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile-MedHeadBackEnd
    container_name: medheadback
    ports:
      - 8081:8081
    networks:
      - my_net
    environment:
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - DATABASE_URL=jdbc:mysql://medheadsql:3306/medhead
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password

  frontend:
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: Dockerfile-MedHeadFrontEnd
    container_name: medheadfront
    ports:
      - 3000:3000
    environment:
      - REACT_APP_PORT=8081
      - REACT_APP_HOST=localhost

volumes:
  data: