apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: "medhead"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql
            - secretRef:
                name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-database-storage
      volumes:
        - name: mysql-database-storage
          persistentVolumeClaim:
            claimName: mysql-volume

      